### ISSUE TITLE
No conversion from UniTuple(array(int64, 1d, C) x 2) to UniTuple(array(int32, 1d, C) x 2) for '$376return_value.9', defined at None

### ISSUE THREAD

**Issue by crobbins327** [MathOnco/valis#10]
Hi,

I am getting this numba error after trying to import valis after setup in a virtual environment:

>>> import valis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cjr66\valis\lib\site-packages\valis\__init__.py", line 6, in <module>
    from . import non_rigid_registrars
  File "C:\Users\cjr66\valis\lib\site-packages\valis\non_rigid_registrars.py", line 16, in <module>
    from . import viz
  File "C:\Users\cjr66\valis\lib\site-packages\valis\viz.py", line 107, in <module>
    def get_grid(shape, grid_spacing, thickness=1):
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\decorators.py", line 219, in wrapper
    disp.compile(sig)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\dispatcher.py", line 129, in compile
    raise retval
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler.py", line 499, in _compile_core
    raise e
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "C:\Users\cjr66\valis\lib\site-packages\numba\core\typeinfer.py", line 1086, in propagate
    raise errors[0]

**numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No conversion from UniTuple(array(int64, 1d, C) x 2) to UniTuple(array(int32, 1d, C) x 2) for '$376return_value.9', defined at None**

File "valis\lib\site-packages\valis\viz.py", line 162:
def get_grid(shape, grid_spacing, thickness=1):
    <source elided>

    return np.array(all_rows), np.array(all_cols)
    ^

During: typing of assignment at C:\Users\cjr66\valis\lib\site-packages\valis\viz.py (162)

File "valis\lib\site-packages\valis\viz.py", line 162:
def get_grid(shape, grid_spacing, thickness=1):
    <source elided>

    return np.array(all_rows), np.array(all_cols)

I have tried this using a pip venv and conda venv and get the same numba error. My numba doesn't like this UniTuple conversion, but I'm not familiar enough with numba or the valis code to fix this. This could also be a problem with my numba version.

Here are the package versions in this pip venv:
Package               Version
--------------------- -----------
beautifulsoup4        4.11.1
bioformats-jar        2020.5.27
cffi                  1.15.1
colorama              0.4.5
colour-science        0.4.1
cycler                0.11.0
dnspython             2.2.1
elementpath           2.5.3
email-validator       1.2.1
fastcluster           1.2.6
fonttools             4.34.4
idna                  3.3
imageio               2.21.0
importlib-metadata    4.12.0
interpolation         2.2.1
jgo                   1.0.4
joblib                1.1.0
JPype1                1.4.0
kiwisolver            1.4.4
llvmlite              0.39.0
lxml                  4.9.1
matplotlib            3.5.2
networkx              2.8.5
numba                 0.56.0
numpy                 1.22.4
ome-types             0.3.0
opencv-contrib-python 4.6.0.66
packaging             21.3
pandas                1.4.3
Pillow                9.2.0
Pint                  0.19.2
pip                   22.2.1
psutil                5.9.1
pycparser             2.21
pydantic              1.9.1
pyparsing             3.0.9
python-dateutil       2.8.2
pytz                  2022.1
pyvips                2.2.1
PyWavelets            1.3.0
scikit-image          0.19.3
scikit-learn          1.1.1
scipy                 1.9.0
scyjava               1.5.1
setuptools            49.2.1
Shapely               1.8.2
SimpleITK             2.1.1.2
six                   1.16.0
soupsieve             2.3.2.post1
Tempita               0.5.2
threadpoolctl         3.1.0
tifffile              2022.7.31
tqdm                  4.64.0
typing_extensions     4.3.0
valis-wsi             1.0.0rc8
weightedstats         0.4.1
xmlschema             1.11.3
zipp                  3.8.1

I will keep trying to troubleshoot on my end.

Thank you for the work on this package, looking forward to using it!

**Comment by cdgatenbee** [comment]
Hi @crobbins327, 

Thanks for bringing this to my attention. This looks similar to an issue that was brought up in a recent merge request. I haven't merged yet, but I've implemented a fix and will include it in the next update, which should be in the next day or two. I _think_ it might have something to do with numba not working quite the same on mac and windows, but I'm not sure. I'll let you know when the update has been pushed, but if you're still having issues afterwards please let me know.

Best,
-Chandler

**Comment by crobbins327** [comment]
Ok, good to know Chandler. Thank you for your prompt response. I'll try setting up on Linux then. 

Cheers,
Jack

**Comment by crobbins327** [comment]
Just commenting to confirm that the package setup  works on Linux. Seems to be a platform error on windows.

Thank you again for this work!

**Comment by cdgatenbee** [comment]
Glad to hear that was the issue! Should have the patch up shortly, but will close this issue for now.
