### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by ciaobladoo** [MathOnco/valis#102]
Hi Chandler,

For some pairs of images we are trying to register I am getting this error. Would you please shed light on what the issue could be?

`Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/valis/registration.py", line 4203, in register
    rigid_registrar = self.rigid_register()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/valis/registration.py", line 3058, in rigid_register
    rigid_registrar = serial_rigid.register_images(self.processed_dir,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/valis/serial_rigid.py", line 1583, in register_images
    registrar.finalize()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/valis/serial_rigid.py", line 1255, in finalize
    w = int(np.ceil(max_x - min_x))
ValueError: cannot convert float NaN to integer`

**Comment by cdgatenbee** [comment]
Hi @ciaobladoo,
Sorry for the delay in getting back to you. It's a little difficult to determine why this would be happening, but based on that message it looks like either one of the images' shape was recorded as `NaN`, or one of the rigid transformation matrices has a `NaN` in it. Why that would happen isn't totally clear though. Is this something you're running into often?  This step uses the images in the "processed" folder, so if you would be willing share those I could take a look and try to replicate this issue. 

Best,
-Chandler

**Comment by ciaobladoo** [comment]
Thanks @cdgatenbee. Yes this error happens to a lot of my image pairs. Here is an example of processed images.
![processed_img1](https://github.com/MathOnco/valis/assets/27153066/ebc4f1f8-ce67-42e3-bb59-ec55435cb376)
![processed_img2](https://github.com/MathOnco/valis/assets/27153066/cc6dcf5e-9d8c-441f-844d-cf2fba9ec31d)

**Comment by ciaobladoo** [comment]
Hi @cdgatenbee. I think this is a permission issue on Databricks - probably the processed images cannot be opened when needed. Closing it down.
