### ISSUE TITLE
Key Error encountered during Rigid Registration

### ISSUE THREAD

**Issue by ciaobladoo** [MathOnco/valis#104]
==== Rigid registration

Traceback (most recent call last):
  File "/home/ssm-user/.local/lib/python3.10/site-packages/valis/registration.py", line 4203, in register
    rigid_registrar = self.rigid_register()
  File "/home/ssm-user/.local/lib/python3.10/site-packages/valis/registration.py", line 3058, in rigid_register
    rigid_registrar = serial_rigid.register_images(self.processed_dir,
  File "/home/ssm-user/.local/lib/python3.10/site-packages/valis/serial_rigid.py", line 1551, in register_images
    registrar.build_metric_matrix(metric=similarity_metric)
  File "/home/ssm-user/.local/lib/python3.10/site-packages/valis/serial_rigid.py", line 863, in build_metric_matrix
    s = obj1.match_dict[obj2].n_matches
KeyError: <valis.serial_rigid.ZImage object at 0x7f33b0128850>

Any clue on what could have caused this? Seems to me the images might be corrupted but I am not sure.

Thank you!

**Comment by cdgatenbee** [comment]
Hi @ciaobladoo, any chance these are similar to the images you shared in issue [102](https://github.com/MathOnco/valis/issues/102)?

**Comment by ciaobladoo** [comment]
Yeah. This is the same image as in issue 102. However, when I was working on Databricks, there are multiple pairs where issue 102 occur. Now I am working on AWS and so far most pairs are successfully registered while this one give me the errors above.
