### ISSUE TITLE
Zen 3.8+ Incompatibility

### ISSUE THREAD

**Issue by Justin-Krieg** [MathOnco/valis#159]
Hi Chandler, issue 2/2

This issue has occurred before my issues with the docker install, but essentially any czi file generated with zen 3.8 or later (were now on version 3.11) wont work with VALIS. I get this error when I try and align images generated from zen 3.11:
```

UserWarning: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 2097834 out of bounds for byte[2097152]
  warnings.warn(warning_msg, warning_type)
Traceback (most recent call last):
  File "ImageReader.java", line 449, in loci.formats.ImageReader.openBytes
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/src/valis/slide_io.py", line 1141, in tile2vips_threaded
    tile = self.slide2image(level, series, xywh=tuple(xywh), z=z, t=t)
  File "/usr/local/src/valis/slide_io.py", line 1267, in slide2image
    img = self._read_multichannel(rdr=rdr, xywh=xywh, z=z, t=t)
  File "/usr/local/src/valis/slide_io.py", line 1356, in _read_multichannel
    buffer = rdr.openBytes(idx, *xywh)
java.lang.java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 2097834 out of bounds for byte[2097152]
```

I’m fairly convinced this [thread ](https://forum.image.sc/t/pb-when-i-open-czi-stitching-image/87585/32)is relating to the same issues, seemingly revolving around changes to rounding from the zen software. 
I’ve uploaded to a [google drive](https://drive.google.com/drive/folders/1Xk1Z3tKt0W-AAqfZJWpieuCLZBDP4Qzb) the same image generated in zen 3.7 which i've then converted to v3.10 to help with the diagnosis.

**Comment by cdgatenbee** [comment]
Thanks for bringing this to my attention @Justin-Krieg, and for sharing the images, which should be very helpful in debugging this. Also, thanks for the update on your other issue, I'm glad to hear it was a fairly straightforward fix, and I'll try to push the updated Dockerfile and Docker image soon.

Best,
-Chandler
