### ISSUE TITLE
pyvips.error.Error: affine does not support optional argument premultiplied

### ISSUE THREAD

**Issue by tkobayashi6** [MathOnco/valis#16]
Hi, @cdgatenbee

I would like to use your VALIS tool for non-rigid registration of H&E and IHC images. However, I am getting the following error during the process, and I am not sure why.
Is there any solution to this error?

Our experimental conditions are as follows.
There are a HE stained image and two IHC images in slide_src_dir.

### Code
```python
registrar = registration.Valis(slide_src_dir, results_dst_dir, reference_img_f=reference_slide, align_to_reference=True)
rigid_registrar, non_rigid_registrar, error_df = registrar.register()
```

### Error
```
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.

==== Converting images

100%|██████████| 3/3 [00:03<00:00,  1.15s/it]
/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/valtils.py:75: UserWarning:

Smallest image is less than max_image_dim_px. parameter max_image_dim_px is being set to 600

/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/valtils.py:75: UserWarning:

parameter max_processed_image_dim_px also being updated to 600


==== Processing images

100%|██████████| 3/3 [00:01<00:00,  2.06it/s]

==== Normalizing images

100%|██████████| 3/3 [00:00<00:00, 40.82it/s]

==== Rigid registraration

100%|██████████| 3/3 [00:00<00:00, 18.35it/s]

======== Detecting features

100%|██████████| 3/3 [00:07<00:00,  2.41s/it]

======== Matching images

100%|██████████| 3/3 [00:00<00:00,  4.85it/s]

======== Sorting images


======== Calculating transformations

100%|██████████| 2/2 [00:00<00:00, 855.37it/s]
100%|██████████| 3/3 [00:00<00:00, 5322.72it/s]
/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/valtils.py:75: UserWarning:

affine does not support optional argument premultiplied
  

Traceback (most recent call last):
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/registration.py", line 3359, in register
    rigid_registrar = self.rigid_register()
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/registration.py", line 2404, in rigid_register
    rigid_registrar = serial_rigid.register_images(self.processed_dir,
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/serial_rigid.py", line 1405, in register_images
    registrar.finalize()
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/serial_rigid.py", line 1111, in finalize
    img_obj.registered_img = warp_tools.warp_img(img=img_obj.image,
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/warp_tools.py", line 987, in warp_img
    affine_warped = img.affine(vips_M,
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/pyvips/vimage.py", line 1347, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/home/USERNAME/miniconda3/envs/colon_ts/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: affine does not support optional argument premultiplied
  

JVM has been killed. If this was due to an error, then a new Python session will need to be started
```

**Comment by tkobayashi6** [comment]
In addition to the above situation, I get the following error when using [register_ihc.py](https://github.com/MathOnco/valis/blob/fa171f784915010fe51044f25014fbb61a6fa9a4/examples/register_ihc.py) you have provided.

```
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.

==== Converting images

  0%|          | 0/5 [00:00<?, ?it/s]
/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/valtils.py:75: UserWarning: VipsForeignLoadTiffFile does not support optional argument subifd
  
  warnings.warn(warning_msg, warning_type)
Traceback (most recent call last):
  File "/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/registration.py", line 3350, in register
    self.convert_imgs(series=self.series, reader_cls=reader_cls)
  File "/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/registration.py", line 1815, in convert_imgs
    vips_img = reader.slide2vips(level=level)
  File "/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/slide_io.py", line 1383, in slide2vips
    vips_slide = self._slide2vips_ome_one_series(level=level, *args, **kwargs)
  File "/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/slide_io.py", line 1340, in _slide2vips_ome_one_series
    toilet_roll = pyvips.Image.new_from_file(self.src_f, n=-1, subifd=level-1)
  File "/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/pyvips/vimage.py", line 352, in new_from_file
    return pyvips.Operation.call(name, filename,
  File "/home/biomy-localpc/miniconda3/envs/colon_ts/lib/python3.9/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: VipsForeignLoadTiffFile does not support optional argument subifd
  

JVM has been killed. If this was due to an error, then a new Python session will need to be started
regisration time is 0.03028773864110311 minutes
0it [00:00, ?it/s]
saving 0 slides took 4.5680999755859374e-05 minutes
JVM has been killed. If this was due to an error, then a new Python session will need to be started
```

**Comment by cdgatenbee** [comment]
Hello @tkobayashi6 ,
Thank you for reporting this. It looks like this may have something to do with the version of pyvips and/or libvips being used. I think this because "premultiplied" has been an argument for pyvips.Image.affine since version 8.10, and support for subIFDs was also added by version 8.10 (https://fossies.org/linux/vips/ChangeLog).

Would you be able to tell me which versions of pyvips and libvips you are using? You should be able to find the pyvips version just by checking 

```
import pyvips
pyvips.__version__
```

and libvips by 

```
from valis import valtils
valtils.get_vips_version()
```

Best,
Chandler

**Comment by tkobayashi6** [comment]
Thank you for your prompt response.

* pivips=='2.2.1'

I got the following error about libvips.

```python
from valis import valtils
valtils.get_vips_version()
```

```shell
      1333 # %%
      1334 from valis import valtils
----> 1335 valtils.get_vips_version()

File ~/miniconda3/envs/colon_ts/lib/python3.9/site-packages/valis/valtils.py:145, in get_vips_version()
    144 def get_vips_version():
--> 145     v = (f"{pyvips.vips_lib.VIPS_MAJOR_VERSION}."
    146          f"{pyvips.vips_lib.VIPS_MINOR_VERSION}."
    147          f"{pyvips.vips_lib.VIPS_MICRO_VERSION}")
    149     return v

File ~/miniconda3/envs/colon_ts/lib/python3.9/site-packages/cffi/api.py:912, in _make_ffi_library.<locals>.FFILibrary.__getattr__(self, name)
    911 def __getattr__(self, name):
--> 912     make_accessor(name)
    913     return getattr(self, name)

File ~/miniconda3/envs/colon_ts/lib/python3.9/site-packages/cffi/api.py:907, in _make_ffi_library.<locals>.make_accessor(name)
    905     update_accessors()
    906     if name not in accessors:
--> 907         raise AttributeError(name)
    908 accessors[name](name)

AttributeError: VIPS_MAJOR_VERSION
```

But I installed **v8.13.1** from the official tar file.
https://github.com/libvips/libvips/releases

**Comment by cdgatenbee** [comment]
Hmm, that's really strange. Could you maybe check the libvips version using:

```
 f"{pyvips.vips_lib.vips_version(0)}.{pyvips.vips_lib.vips_version(1)}.{pyvips.vips_lib.vips_version(2)}"
```
I think it can be possible for to there to be different versions of libvips on the system (perhaps one installed by a different packge), so it'd be good to know which one pyvips is using. I'm also using pyvips 2.2.1, which does have the premultiplied argument for Image.affine (https://libvips.github.io/pyvips/vimage.html#pyvips.Image.affine), as well as the pyvips.vips_lib.VIPS_MAJOR_VERSION attribute. From the errors, it looks like pyvips was installed using conda. Is that correct? If so, I'll try installing pyvips in a new conda environment to see if i can replicate the error.

Best,
-Chandler

**Comment by tkobayashi6** [comment]
I installed pyvips with pip, but I may have installed a duplicate package when I built the VALIS environment.
I would like to try again in a new virtual environment.

**Comment by tkobayashi6** [comment]
I set up the VALIS environment in a new virtual environment and it worked well.
Thank you so much for your quick and kind response!

**Comment by cdgatenbee** [comment]
great! So glad to hear you were able to get it working. If you run into any other issues just let me know, but I'll go ahead and close this issue.
