### ISSUE TITLE
Bug when warping and merging?

### ISSUE THREAD

**Issue by simomounir** [MathOnco/valis#166]
Hi again,

Thanks for helping always with hickups we encounter.

Rigid and Non-rigid registration were run successfully, then I ran into this error when attempting to warp and merge the slides to create a composite. 

###############

2024-10-16 04:19:09 merging DAPI from DAPI
2024-10-16 04:19:09 merging DAPI from HnE
2024-10-16 04:19:09 Traceback (most recent call last):
2024-10-16 04:19:09   File "/Resolve/basic_registration.py", line 219, in <module>
2024-10-16 04:19:09     main()
2024-10-16 04:19:09   File "/Resolve/basic_registration.py", line 203, in main
2024-10-16 04:19:09     registrar.warp_and_merge_slides(dst_f=merged_slide_dst_f,
2024-10-16 04:19:09   File "/usr/local/src/valis/valtils.py", line 36, in wrapper
2024-10-16 04:19:09     return f(*args, **kwargs)
2024-10-16 04:19:09            ^^^^^^^^^^^^^^^^^^
2024-10-16 04:19:09   File "/usr/local/src/valis/registration.py", line 5197, in warp_and_merge_slides
2024-10-16 04:19:09     ome_xml_obj = slide_io.create_ome_xml(out_xyczt, bf_dtype, is_rgb=False,
2024-10-16 04:19:09                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-16 04:19:09   File "/usr/local/src/valis/slide_io.py", line 3222, in create_ome_xml
2024-10-16 04:19:09     updated_channel_names = check_channel_names(channel_names, is_rgb, nc=c)
2024-10-16 04:19:09                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-16 04:19:09   File "/usr/local/src/valis/slide_io.py", line 3149, in check_channel_names
2024-10-16 04:19:09     (channel_names[i] is not None and channel_names[i] != "None")
2024-10-16 04:19:09      ~~~~~~~~~~~~~^^^
2024-10-16 04:19:09 IndexError: list index out of range

###########

Here is the full attempted code:

***************************************************************************************************************************************
    registrar = registration.Valis(src_dir=slide_src_dir, dst_dir=results_dst_dir, reference_img_f=reference_img_file, align_to_reference=True, imgs_ordered=False)

    rigid_registrar, non_rigid_registrar, error_df = registrar.register()

    #time.sleep(1000)

    elapsed = time.time() - start
    print(f"regisration time is {elapsed/60} minutes")

    # Check results in registered_slide_dst_dir. If they look good, export the registered slides
    registered_slide_dst_dir = os.path.join("/usr/local/src/valis/expected_results/registered_slides", registrar.name)
    registered_slide_dst_dir_2 = os.path.join(results_dst_dir, registrar.name

    def cnames_from_filename(src_f):
        """Get channel names from file name
        Note that the DAPI channel is not part of the filename
        but is always the first channel.
        """

        f = valtils.get_name(src_f)
        print(f"f: {f}")
        return ["DAPI"] + f.split(" ")[1:4]

    channel_name_dict = {f:cnames_from_filename(f) for f in registrar.original_img_list}

    #channel_name_dict

    print(f"channels dict: {channel_name_dict}")

    print("warp and merge slides")
    registrar.warp_and_merge_slides(dst_f=merged_slide_dst_f,
                                    channel_name_dict=channel_name_dict,
                                    drop_duplicates=True) #false

******************************************************************************************************************************

Thanks for your help!

**Comment by cdgatenbee** [comment]
Hi @simomounir,
Many apologies for taking so long to respond, it's been a very busy couple of weeks. Regarding this issue, based on the error log, it looks like the error may be related to the function being used to get the channel names (`cnames_from_filename`). In the example, the channel names are part of the file names (e.g. "examples/example_datasets/CD4 CD68 CD3.ome.tiff"), except for DAPI, which gets added to the list of channel names produced by `cnames_from_filename`. For example, if `src_f="CD4 CD68 CD3.ome.tiff"` then `cnames_from_filename` will produce a list of channel names that is ["DAPI", "CD4", "CD68", "CD3"]. So, `cnames_from_filename` will only produce the correct channel names if your files are named the same. This probably isn't the case, so there are 3 other options: 

1. Set the `channel_name_dict=None`, and valis will try to use the channel names in each slide's metadata (sometimes the antibody names, but other times the fluorophore). If no channel names are found, they will be set to C0, C1, C2, etc...
2. Replace `cnames_from_filename ` with a custom function that can determine what the channel names are for each image
3. Manually define what the channels names should be for each slide, and use that to populate `channel_name_dict `.

Please try out one of the above and let me know if you continue to have issues.

Best,
-Chandler
