### ISSUE TITLE
How is keypoint detection specified as a Superpoint method？

### ISSUE THREAD

**Issue by zhahaha123** [MathOnco/valis#172]
Hello, I got an error trying to use the SuperPoint method as a keypoint detection method. Could you help me see what the problem is

My code：
from valis import registration, feature_detectors, non_rigid_registrars, affine_optimizer
slide_src_dir = "/disk3/zsm/wsi&reconstruction/code_test/partial_20_test_thumbnails"
results_dst_dir = "/disk3/zsm/wsi&reconstruction/code_test/1208_superPoint_test"
registered_slide_dst_dir = "/disk3/zsm/wsi&reconstruction/code_test/1208_superPoint_test/registered_slides"

feature_detector_cls = feature_detectors.SuperPointFD
affine_optimizer_cls = affine_optimizer.AffineOptimizerMattesMI

# Create a Valis object and use it to register the slides in slide_src_dir

registrar = registration.Valis(slide_src_dir, results_dst_dir,
                               feature_detector_cls=feature_detector_cls,
                               affine_optimizer_cls=affine_optimizer_cls,)
                              
rigid_registrar, non_rigid_registrar, error_df = registrar.register()

registration.kill_jvm() # Kill the JVM

error：
Traceback (most recent call last):
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/registration.py", line 4608, in register
    rigid_registrar = self.rigid_register()
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/registration.py", line 3291, in rigid_register
    rigid_registrar = serial_rigid.register_images(self.processed_dir,
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/serial_rigid.py", line 1521, in register_images
    registrar.generate_img_obj_list(feature_detector, qt_emitter=qt_emitter)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/serial_rigid.py", line 514, in generate_img_obj_list
    img_obj.kp_pos_xy, img_obj.desc = feature_detector.detect_and_compute(img)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/feature_detectors.py", line 510, in detect_and_compute
    kp_pos_xy, desc = self.detect_and_compute_sg(img)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/feature_detectors.py", line 501, in detect_and_compute_sg
    pred = superpoint_obj({'image': inp})
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/valis/superglue_models/superpoint.py", line 155, in forward
    x = self.relu(self.conv1a(data['image']))
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/disk1/zsm/anaconda3/envs/valis/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by cdgatenbee** [comment]
Hi @zhahaha123, 

It looks like the issue is that the image is on the GPU but the weights on on the CPU. I'm not sure why that would be happening though, as the `SuperPointFD` should be sending both to the same device. This could probably be avoided by setting `force_cpu=True` when initializing `SuperPointFD`, but unfortunately that isn't possible at the moment, as currently the feature detector objects are initialized during the registration process. However, the next of release of valis does support passing in instantiated feature detectors, so it should work in the next update. I've also added Disk and DeDoDe feature detectors as well, which seem to offer better performance that SuperPoint and the other feature detectors currently available in valis. I'm hoping to push that release in the next week or so, so hopefully that will resolve this issue. 

Best,
-Chandler

**Comment by zhahaha123** [comment]
Thank you very much for your answer, I will try according to your suggestion
