### ISSUE TITLE
Wrong 1.1.0 docker image

### ISSUE THREAD

**Issue by huboqiang** [MathOnco/valis#176]
Hi, previous image worked well for me, but I don't know what's wrong with the 1.1.0 image. :

```
docker pull cdgatenbee/valis-wsi:1.1.0
docker run --platform linux/amd64 -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/Downloads:/output \
    --privileged -t --rm \
    quay.io/singularity/docker2singularity:stable \
    cdgatenbee/valis-wsi:1.1.0
```

```
>>> import pyvips
Traceback (most recent call last):
  File "/usr/local/src/.venv/lib/python3.12/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ImportError: librsvg-2.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/src/.venv/lib/python3.12/site-packages/pyvips/__init__.py", line 61, in <module>
    vips_lib = ffi.dlopen('libvips.so.42')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/.venv/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/.venv/lib/python3.12/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/src/.venv/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': librsvg-2.so.2: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'```

I'm looking forward for your suggenstions~

**Comment by cdgatenbee** [comment]
Hi @huboqiang,
Unfortunately, there are a few issues with the current Docker container that I'm working on resolving. However, I think this particular issue may be overcome using the updated Dockerfile created by @Gibbsdavidl. I just merged it, so the updated Dockerfile can be found [here](https://github.com/MathOnco/valis/blob/main/Dockerfile). There are still a few updates I'm working on to that I need to complete before pushing an updated Docker image. However, you should be able to use that Docker file to create a Docker image that won't produce these errors, although you will also need to download the valis [source code](https://github.com/MathOnco/valis/tree/main/valis) to the same directory as the Docker file before you build the new image. Very sorry this is a hassle, and thank you for your patience.

Best,
-Chandler

**Comment by huboqiang** [comment]
Thank you Chandler and I'll try to build.

**Comment by ziyuanzhao2000** [comment]
I encountered the same issue...is there any update on this? Can we have an updated docker image that can run without the error?

**Comment by moataz-youssef** [comment]
If anyone is using Singularity instead of Docker, here is my .def file to create a new image based on Ubuntu 24.04. You need to have the folder with the source code of Valis in the same folder where you are running the command.

```
Bootstrap: docker
From: ubuntu:24.04

#%setup
#    mkdir -p /usr/local/src/valis

%files
    valis /usr/local/src/valis
    pyproject.toml /usr/local/src/pyproject.toml
    README.rst /usr/local/src/README.rst
    LICENSE.txt /usr/local/src/LICENSE.txt
    CITATION.cff /usr/local/src/CITATION.cff

%post
    export DEBIAN_FRONTEND=noninteractive

    mkdir -p /usr/local/src/valis

    # Install dependencies
    apt-get update \
        && apt-get install -y \
        build-essential \
        software-properties-common \
        ninja-build \
        python3-pip \
        bc \
        wget \
        ca-certificates \
        git-all \
        cmake \
        libjxr-dev \
        openjdk-11-jre \
        python3-venv \
        libglib2.0-dev \
        glib-2.0-dev \
        libexpat1-dev \
        libexpat-dev \
        librsvg2-2 \
        librsvg2-common \
        librsvg2-dev \
        libpng-dev \
        libjpeg-turbo8-dev \
        libopenjp2-7-dev \
        libtiff-dev \
        libexif-dev \
        liblcms2-dev \
        libheif-dev \
        liborc-dev \
        libgirepository1.0-dev \
        libopenslide-dev \
        libvips42 \
        gfortran \
	pkg-config

    # Manually compile OpenBLAS with increased MAX_THREADS
    cd /usr/local/src
    git clone --depth=1 https://github.com/xianyi/OpenBLAS.git
    cd OpenBLAS
    make USE_OPENMP=1 -j$(nproc)
    make install PREFIX=/usr/local

    # Verify OpenBLAS installation
    echo "/usr/local/lib" > /etc/ld.so.conf.d/openblas.conf
    ldconfig
    ls -l /usr/local/lib/libopenblas*

    # Detect OpenBLAS location
	OPENBLAS=$(find /usr/local/lib -name 'libopenblas.so' | head -n 1 || echo "")

	if [[ -z "$OPENBLAS" ]]; then
		echo "Error: OpenBLAS not found!" >&2
		exit 1
	fi


    echo "Detected OpenBLAS: $OPENBLAS"

    # Set environment variables to ensure NumPy links to the new OpenBLAS
    # Set environment variables for OpenBLAS
    export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
    export BLAS="/usr/local/lib/libopenblas.so"
    export LAPACK="/usr/local/lib/libopenblas.so"
    export NPY_BLAS_ORDER=openblas
    export NPY_LAPACK_ORDER=openblas
    export OPENBLAS_NUM_THREADS=$(nproc)

    # Set up virtual environment
    python3 -m venv /usr/local/src/.venv
    export PATH="/usr/local/src/.venv/bin:$PATH"

    # Upgrade pip and install Poetry
    /usr/local/src/.venv/bin/pip install --upgrade pip
    /usr/local/src/.venv/bin/pip install "poetry>=1.6.1"

    # Activate virtual environment
    . /usr/local/src/.venv/bin/activate

    # Ensure Poetry uses the in-project virtual environment
    poetry config virtualenvs.in-project true

    # Install Python dependencies from pyproject.toml
    cd /usr/local/src

    # Upgrade or downgrade certain packages without changing anything else
    sed -i 's/scikit-image = "^0.19.3"/scikit-image = "^0.24.0"/g' pyproject.toml
	# sed -i 's/numpy = "[^"]*"/numpy = "<2"/g' pyproject.toml
	sed -i 's/torch = "[^"]*"/torch = "2.2.0"/g' pyproject.toml

    # Install poetry dependencies
    poetry install --only main
	
	# Force NumPy to use the compiled OpenBLAS
    pip install --no-cache-dir meson meson-python ninja "cython>=0.29.36" pyyaml
	pip install --no-cache-dir "numpy<2" --no-binary :all: --no-build-isolation --compile

    # Download Bio-Formats JAR file
    wget https://downloads.openmicroscopy.org/bio-formats/7.0.0/artifacts/bioformats_package.jar -P /usr/local/src/valis

    # Set Matplotlib cache directory to a writable location
    export MPLCONFIGDIR="/tmp/matplotlib"

    # Cleanup
    apt-get remove -y wget build-essential ninja-build && \
    apt-get autoremove -y && \
    apt-get autoclean && \
    apt-get clean

%environment
    # Set environment variables for container execution
    export FONTCONFIG_PATH=/tmp/.fontconfig
    export XDG_CACHE_HOME=/tmp/.cache
    export PATH="/usr/local/src/.venv/bin:$PATH"
    export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
    export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
    export OPENBLAS_NUM_THREADS=$(nproc)
    export BLAS="/usr/local/lib/libopenblas.so"
    export LAPACK="/usr/local/lib/libopenblas.so"
    export NPY_BLAS_ORDER=openblas
    export NPY_LAPACK_ORDER=openblas
    export MPLCONFIGDIR="/tmp/matplotlib"

%test
    # Run a quick test to ensure valis is installed
    python3 -c "import valis"
	python3 -c "import numpy; numpy.__config__.show()"
```

I had problems with OpenBLAS and NumPy that's why I am building them from source on my hardware. More here: https://github.com/MathOnco/valis/issues/188

**Comment by cdgatenbee** [comment]
Thanks for sharing this here, @moataz-youssef!

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi everybody, 
Wanted to let you know that the updated version of Valis (1.2.0) is now on Dockerhub. I've updated the Docker testing to be more robust, so hopefully the Docker related issues have been resolved. Please let me know if you're still having issues though.

Best,
-Chandler
