### ISSUE TITLE
extract_area: bad extract area Error

### ISSUE THREAD

**Issue by matthiaskoenig** [MathOnco/valis#67]
Hi all,

thanks for the great library. Things work for most of my slides, but for one example I get the following error when trying to save the slides.
Registration works fine and results are attached, but when trying to write things break.

Valis results are attached. I can share the wsi tomorrow.
[pig_SSES2012-14.zip](https://github.com/MathOnco/valis/files/12318003/pig_SSES2012-14.zip)
```
Traceback (most recent call last):
  File "/home/mkoenig/git/zonation-image-analysis/src/zia/slide_alignment/valis_example.py", line 57, in <module>
    registrar.warp_and_save_slides(
  File "/usr/local/src/valis/valtils.py", line 29, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/src/valis/registration.py", line 4332, in warp_and_save_slides
    slide_obj.warp_and_save_slide(dst_f=dst_f, level = level,
  File "/usr/local/src/valis/valtils.py", line 29, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/src/valis/registration.py", line 961, in warp_and_save_slide
    warped_slide = self.warp_slide(level=level, non_rigid=non_rigid,
  File "/usr/local/src/valis/valtils.py", line 29, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/src/valis/registration.py", line 892, in warp_slide
    warped_slide = slide_tools.warp_slide(src_f, M=self.M,
  File "/usr/local/src/valis/slide_tools.py", line 288, in warp_slide
    vips_warped = warp_tools.warp_img(img=vips_slide, M=M, bk_dxdy=dxdy,
  File "/usr/local/src/valis/warp_tools.py", line 1095, in warp_img
    warped = warped.extract_area(*bbox_xywh)
  File "/usr/local/src/.venv/lib/python3.10/site-packages/pyvips/vimage.py", line 1347, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/local/src/.venv/lib/python3.10/site-packages/pyvips/voperation.py", line 305, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call extract_area
  extract_area: bad extract area
```

Best Matthias

**Comment by cdgatenbee** [comment]
Thanks for sharing the valis results, @matthiaskoenig, it looks like the registration worked ok. I'll look into the other error once you are able to share the wsi.

Best,
-Chandler

**Comment by matthiaskoenig** [comment]
Thanks for the help. We implemented a ROI detection and ROI separation which solved some of the alignment issues and also this issue. Thanks for your help.

**Comment by cdgatenbee** [comment]
Hi @ViriatoII, 
Sorry you're running into this issue. Is this happening with all of your images, or a subset? I've made some changes to this part of the code as part of the next update, so it may fix the issue. But if you're able to share a pair of images this is happening with I could test the current code base before pushing that update.

Best,
-Chandler

**Comment by ViriatoII** [comment]
Hey Chandler,

Thank you for the very prompt reply! This is happening with my first test dataset, only 2 downscaled images. I'm leaving them [here](https://we.tl/t-6Ah7xPRRsh) available for download in the next 7 days.

Description for the images, and my suspicion for the origin of the problem: 
Both images are single channel. The first image is much wider and less zoom.  The second image is then contained in the first one, but it also has missing tiles.

The *rigid_overlap image in the results shows that the correct registration is achieved, automatically taking different zoom levels and rotation into account (amazing!).

![image](https://github.com/MathOnco/valis/assets/25958099/204fa7ed-859a-41b5-97b0-30bd30a29910)


 Looking at the mask image of the second image (below), I see that the missing tiles are correctly not inside the mask area. But those mask edges look very fuzzy, maybe they are doing curves and very small loops, in which case area extraction would crash? 

![image](https://github.com/MathOnco/valis/assets/25958099/dde0e84b-505e-4c9d-b63e-a030a7e09189)

**Comment by cdgatenbee** [comment]
Hi @ViriatoII,
Sorry for the inconvenience, but would you be able to re-upload the images? I missed the fact that the link expires and waited too long to download :( 

-Chandler
