### ISSUE TITLE
UnboundLocalError: local variable 'reader' referenced before assignment

### ISSUE THREAD

**Issue by daviddaiweizhang** [MathOnco/valis#84]
I am trying to register two jpg images whose resolutions are about 30k x 30k. One is an RGB image while the other is a greyscale image. This is the script I used:
```
from valis.registration import Valis

registrar = Valis(
        src_dir=dir_slides,
        dst_dir=dir_results,
        imgs_ordered=True,
        img_list=slide_paths)
registrar_rigid, registrar_nonrigid, error_df = registrar.register()
```

I received the following error:

```
(process:111295): VIPS-WARNING **: 23:17:22.529: unable to load "/appl/vips-8.14.2/lib64/vips-modules-8.14/vips-magick.so" -- libMagickCore-6.Q16.so.6: cannot open shared object file: No such file or directory
/home/myusername/.pyenv/versions/st/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
{'data/lin2021crc/registration/slides/001.jpg': '001', 'data/lin2021crc/registration/slides/002-ag.jpg': '002-ag'}
Registering images...

==== Converting images

Converting images:   0%|                                                                                              | 0/2 [00:00<?, ?image/s]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.
/home/myusername/.pyenv/versions/st/lib/python3.9/site-packages/valis/valtils.py:22: UserWarning: Attempting to get reader for data/lin2021crc/registration/slides/001.jpg created the following error:
'NoneType' object has no attribute 'slide_dimensions'
  warnings.warn(warning_msg, warning_type)
/home/myusername/.pyenv/versions/st/lib/python3.9/site-packages/valis/valtils.py:22: UserWarning: Attempting to read data/lin2021crc/registration/slides/001.jpg created the following error:
local variable 'slide_reader_cls' referenced before assignment
  warnings.warn(warning_msg, warning_type)
Converting images:   0%|                                                                                              | 0/2 [00:03<?, ?image/s]
/home/myusername/.pyenv/versions/st/lib/python3.9/site-packages/valis/valtils.py:22: UserWarning: local variable 'reader' referenced before assignment
  warnings.warn(warning_msg, warning_type)
Traceback (most recent call last):
  File "/home/myusername/.pyenv/versions/st/lib/python3.9/site-packages/valis/registration.py", line 4102, in register
    self.convert_imgs(series=self.series, reader_cls=reader_cls)
  File "/home/myusername/.pyenv/versions/st/lib/python3.9/site-packages/valis/registration.py", line 2295, in convert_imgs
    slide_dims = reader.metadata.slide_dimensions
UnboundLocalError: local variable 'reader' referenced before assignment

JVM has been killed. If this was due to an error, then a new Python session will need to be started
Done.
Saving images: 0image [00:00, ?image/s]
JVM has been killed. If this was due to an error, then a new Python session will need to be started

```

**Comment by cdgatenbee** [comment]
Hi @daviddaiweizhang, 
Sorry you've run into this issue. Based on the error message `(process:111295): VIPS-WARNING **: 23:17:22.529: unable to load "/appl/vips-8.14.2/lib64/vips-modules-8.14/vips-magick.so" -- libMagickCore-6.Q16.so.6: cannot open shared object file: No such file or directory`, it looks valis is trying to use libvips to read your images, but that libvips can't find ImageMagick. Could you check if you have ImageMagick installed? Or, another option might be to force valis to use Bioformats to read your images, which can be done like this:

```
from valis.registration import Valis
from valis.slide_io import BioFormatsSlideReader

registrar = Valis(
        src_dir=dir_slides,
        dst_dir=dir_results,
        imgs_ordered=True,
        img_list=slide_paths)
registrar_rigid, registrar_nonrigid, error_df = registrar.register(reader_cls=BioFormatsSlideReader)
```
Please try one of those and let me know how it goes.

Best,
-Chandler

**Comment by daviddaiweizhang** [comment]
Hi @cdgatenbee,

Thank you for your response. I just checked and found that ImageMagick is installed and working in the command line. I am working with the system administrator to see what has gone wrong with ImageMagick and vips.

Meanwhile, for the alternative solution, I tried your script using Bioformats:

```
from valis.registration import Valis
from valis.slide_io import BioFormatsSlideReader

registrar = Valis(
        src_dir=dir_slides,
        dst_dir=dir_results,
        imgs_ordered=True,
        img_list=slide_paths)
registrar_rigid, registrar_nonrigid, error_df = registrar.register(reader_cls=BioFormatsSlideReader)
```

and I received the following message:

```
(process:77169): VIPS-WARNING **: 22:56:18.433: unable to load "/appl/vips-8.14.2/lib64/vips-modules-8.14/vips-magick.so" -- libMagickCore-6.Q16.so.6: cannot open shared object file: No such file or directory
/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)

==== Converting images
r
Converting images:   0%|                                                                                              | 0/2 [00:00<?, ?image/s]SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.
java.io.IOException: Restart interval and markers invalid
JVM has been killed. If this was due to an error, then a new Python session will need to be started
/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/valtils.py:22: UserWarning: Attempting to read data/lin2021crc/registration/slides/WD-76845-001.jpg created the following error:
'NoneType' object has no attribute 'slide_dimensions'
  warnings.warn(warning_msg, warning_type)
Converting images:   0%|                                                                                              | 0/2 [00:03<?, ?image/s]
/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/valtils.py:22: UserWarning: local variable 'reader' referenced before assignment
  warnings.warn(warning_msg, warning_type)
Traceback (most recent call last):
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/registration.py", line 4102, in register
    self.convert_imgs(series=self.series, reader_cls=reader_cls)
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/registration.py", line 2295, in convert_imgs
    slide_dims = reader.metadata.slide_dimensions
UnboundLocalError: local variable 'reader' referenced before assignment

JVM has been killed. If this was due to an error, then a new Python session will need to be started
```

However, if I remove `imgs_ordered=True` and `img_list=slide_paths` and run 

```
from valis.registration import Valis
from valis.slide_io import BioFormatsSlideReader

registrar = Valis(
        src_dir=dir_slides,
        dst_dir=dir_results)
registrar_rigid, registrar_nonrigid, error_df = registrar.register(reader_cls=BioFormatsSlideReader)
```

I receive a different message:

```
(process:75244): VIPS-WARNING **: 22:52:29.997: unable to load "/appl/vips-8.14.2/lib64/vips-modules-8.14/vips-magick.so" -- libMagickCore-6.Q1
6.so.6: cannot open shared object file: No such file or directory
/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is depr
ecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for mor
e information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.

==== Converting images

Converting images:   0%|                                                                                              | 0/2 [00:00<?, ?image/s]
No series provided. Selecting series with largest image, which is series 0
Converting slide to pyvips image
                                                                                                                                              j
ava.lang.OutOfMemoryError: Java heap space                                                                             | 0/840 [00:00<?, ?it/s]
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Converting images:   0%|                                                                                              | 0/2 [00:46<?, ?image/s]
java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/valtils.py:22: UserWarning: local variable 'tile' referenced before assignme
nt
  warnings.warn(warning_msg, warning_type)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Traceback (most recent call last):
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/registration.py", line 4102, in register
    self.convert_imgs(series=self.series, reader_cls=reader_cls)
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/registration.py", line 2302, in convert_imgs
    vips_img = reader.slide2vips(level=level)
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/slide_io.py", line 966, in slide2vips
    self.get_tiles_parallel(level, tile_bbox, pixel_type, series, z=z, t=t),
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/slide_io.py", line 905, in get_tiles_parallel
    Parallel()(delayed(tile2vips_threaded)(i) for i in tqdm(range(n_tiles)))
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/appl/python-3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/appl/python-3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/daiweiz/.pyenv/versions/st/lib/python3.9/site-packages/valis/slide_io.py", line 900, in tile2vips_threaded
    tile_array[idx] = slide_tools.numpy2vips(tile, self.metadata.pyvips_interpretation)
UnboundLocalError: local variable 'tile' referenced before assignment
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
JVM has been killed. If this was due to an error, then a new Python session will need to be started
 11%|███████████▋                                                                                             | 93/840 [00:52<07:02,  1.77it/s]
```

I was monitoring the memory usage, and the memory used by the program was far below the total memory available.

Thank you!

**Comment by cdgatenbee** [comment]
Hi @daviddaiweizhang,
It looks like maybe there is an issue reading one of your images. What format are they? Would you mind sharing one so that I can try to debug this? If so, you can send me a link over e-mail (Chandler.Gatenbee@moffitt.org) if you would prefer to not make the image public.

Best,
-Chandler

**Comment by daviddaiweizhang** [comment]
Thank you, @cdgatenbee !

I just emailed you the two images:
```
1.jpg JPEG 28673x27162 28673x27162+0+0 8-bit sRGB 132.6MiB 0.000u 0:00.000
2.jpg JPEG 29877x28158 29877x28158+0+0 8-bit Grayscale Gray 256c 67.4615MiB 0.010u 0:00.005
```
In addition, I tried reinstalling ImageMagick and vips. The "vips cannot find ImageMatick" warning is now gone, but the same error message from VALIS is still there:
```
/appl/miniconda3-22.11/envs/valis2/lib/python3.10/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)

==== Converting images

Converting images:   0%|                                      | 0/2 [00:00<?, ?image/s]SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.
/appl/miniconda3-22.11/envs/valis2/lib/python3.10/site-packages/valis/valtils.py:22: UserWarning: Attempting to get reader for data/lin2021crc/registration/slides/WD-76845-001.jpg created the following error:
'NoneType' object has no attribute 'slide_dimensions'
  warnings.warn(warning_msg, warning_type)
/appl/miniconda3-22.11/envs/valis2/lib/python3.10/site-packages/valis/valtils.py:22: UserWarning: Attempting to read data/lin2021crc/registration/slides/WD-76845-001.jpg created the following error:
local variable 'slide_reader_cls' referenced before assignment
  warnings.warn(warning_msg, warning_type)
Converting images:   0%|                                      | 0/2 [00:05<?, ?image/s]
/appl/miniconda3-22.11/envs/valis2/lib/python3.10/site-packages/valis/valtils.py:22: UserWarning: local variable 'reader' referenced before assignment
  warnings.warn(warning_msg, warning_type)
Traceback (most recent call last):
  File "/appl/miniconda3-22.11/envs/valis2/lib/python3.10/site-packages/valis/registration.py", line 4102, in register
    self.convert_imgs(series=self.series, reader_cls=reader_cls)
  File "/appl/miniconda3-22.11/envs/valis2/lib/python3.10/site-packages/valis/registration.py", line 2295, in convert_imgs
    slide_dims = reader.metadata.slide_dimensions
UnboundLocalError: local variable 'reader' referenced before assignment

JVM has been killed. If this was due to an error, then a new Python session will need to be started
```

**Comment by daviddaiweizhang** [comment]
Update: After I converted both images to PNG, the problem was gone, and the results looked fine.

**Comment by cdgatenbee** [comment]
Hi @daviddaiweizhang,
Glad to hear it ended up working out after the png conversion. I'll keep this issue open until I can figure out why the original images weren't working though (thank you again for sharing them). Hopefully afterwards the conversion won't be necessary. 

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi @daviddaiweizhang, 
Wanted to let you know that I was able to recreate your issues with the images you provided (thanks again!). It looks like one of the problems was related to an open Bio-formats issue  https://github.com/ome/bioformats/issues/3773, as I was getting the same "Invalid scanline stride" error when I tried to open the jpegs using Bio-formats. Since vips can read jpegs as well, I've updated valis to give preference to using libvips over bio-formats where possible, which would be faster anyway. Unfortunately, specifying that the `VipsSlideReader` should be used instead won't work in the current version (1.0.2) since there will be erorrs when creating the slide metadata. However, I have updated the code to eliminate those errors, so these large jpegs should work in the next update (1.0.3), and hopefully you won't need to convert them to pngs beforehand. 

As a aside, I found that using H&E stain deconvolution to pre-process the images using  `registrar.register(brightfield_processing_cls=preprocessing.HEDeconvolution)` yielded better non-rigid results than when using the default brightfield preprocessing method. You may already be using that method, but I thought it would be worth mentioning just in case you're using the default pre-processing method.

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi @xb-li, 
I believe that the `premultiplied` argument was added to the `affine` method a little while ago (sorry, not sure which exact version), so could you please check that your pyvips and libvips installations are up to date? As of today (Jan 8, 2024) I believe the most recent versions are pyvips 2.2.2 and libvips 8.15. You can check the your versions with
```
import pyvips
pyvips_ver = pyvips.__version__
libvips_ver=".".join([str(pyvips.vips_lib.vips_version(i)) for i in range(3)])
```
If getting the libvips version didn't work, maybe try:
```
libvips_ver= f"{pyvips.vips_lib.VIPS_MAJOR_VERSION}.{pyvips.vips_lib.VIPS_MINOR_VERSION}.{pyvips.vips_lib.VIPS_MICRO_VERSION}"
```

Best,
-Chandler

**Comment by daviddaiweizhang** [comment]
Hi Chandler,

Thank you for the fixing the bug and the tips on image preprocessing. I look forward to trying the next update of VALIS.

David

**Comment by xb-li** [comment]
> Hi @xb-li, I believe that the `premultiplied` argument was added to the `affine` method a little while ago (sorry, not sure which exact version), so could you please check that your pyvips and libvips installations are up to date? As of today (Jan 8, 2024) I believe the most recent versions are pyvips 2.2.2 and libvips 8.15. You can check the your versions with
> 
> ```
> import pyvips
> pyvips_ver = pyvips.__version__
> libvips_ver=".".join([str(pyvips.vips_lib.vips_version(i)) for i in range(3)])
> ```
> 
> If getting the libvips version didn't work, maybe try:
> 
> ```
> libvips_ver= f"{pyvips.vips_lib.VIPS_MAJOR_VERSION}.{pyvips.vips_lib.VIPS_MINOR_VERSION}.{pyvips.vips_lib.VIPS_MICRO_VERSION}"
> ```
> 
> Best, -Chandler

Thank you very much for your answer.
My project running environment is:
PyTorch 1.10.0
Python 3.8 (ubuntu20.04)
Cuda 11.3
Libvips 8.9
Pyvips 2.2.2
But I don't know how to install libvips 8.15.1. Can you share the installation steps.

**Comment by xb-li** [comment]
Thanks @cdgatenbee 
Thank you very much for your answer.
My project running environment is:
PyTorch 1.10.0
Python 3.8 (ubuntu20.04)
Cuda 11.3
Libvips 8.9
Pyvips 2.2.2
But I don't know how to install libvips 8.15.1. Can you share the installation steps.

**Comment by cdgatenbee** [comment]
Hi @xb-li,
It looks like you're using a conda environment, and the installation instructions on how to install libvips 8.15 via conda can be found [here](https://anaconda.org/conda-forge/libvips). Hopefully after the update the issue with `premultiplied` will be resolved, but please don't hesitate to ask or open a new issue if you run into any problems.

Best,
-Chandler

**Comment by xb-li** [comment]
Hi @cdgatenbee 
Thank you very much for your help. My program can now run.
But in the end, I didn't get the completed result, it seems like a part was missing. The complete code is as follows:
`import time
import os
import numpy as np
from valis import registration, preprocessing
from valis.micro_rigid_registrar import MicroRigidRegistrar # For high resolution rigid registration
import os


#autodl-tmp/test
base = "/root/autodl-tmp/test"
results_dst_dir = "/root/autodl-tmp/test_results"
registered_slide_dst_dir = "/root/autodl-tmp/test_registered"
list = os.listdir(base)
list.sort()
#print(list)

for name in list[1:-1]: 
    slide_src_dir = os.path.join(base,name)
    #slide_src_dir = base+name
    print(slide_src_dir)
    reference_slide = "_HE_"
    micro_reg_fraction = 0.10 # Fraction full resolution used for non-rigid registration
#
    # Perform high resolution rigid registration using the MicroRigidRegistrar
    start = time.time()
    registrar = registration.Valis(slide_src_dir, results_dst_dir, micro_rigid_registrar_cls=MicroRigidRegistrar,align_to_reference=True,reference_img_f=reference_slide)
    rigid_registrar, non_rigid_registrar, error_df = registrar.register(brightfield_processing_cls=preprocessing.StainFlattener,
                                                                        brightfield_processing_kwargs={"adaptive_eq":True, "n_colors":-1})

    # Calculate what `max_non_rigid_registration_dim_px` needs to be to do non-rigid registration on an image that is 25% full resolution.
    ref_slide = registrar.get_ref_slide()
    micro_reg_size = int(micro_reg_fraction*np.max(ref_slide.slide_dimensions_wh[0]))

    # Perform high resolution non-rigid registration using 25% full resolution
    micro_reg, micro_error = registrar.register_micro(max_non_rigid_registration_dim_px=micro_reg_size)

    # Save all registered slides as ome.tiff
    registrar.warp_and_save_slides(registered_slide_dst_dir, crop="overlap")
    print("Finished")
    # Kill the JVM
    registration.kill_jvm()
    
    #libvips_ver= f"{pyvips.vips_lib.VIPS_MAJOR_VERSION}.{pyvips.vips_lib.VIPS_MINOR_VERSION}.{pyvips.vips_lib.VIPS_MICRO_VERSION}"
    #registrar.register(brightfield_processing_cls=preprocessing.HEDeconvolution)`
The process is shown in the picture:
![微信图片_20240113084737](https://github.com/MathOnco/valis/assets/92066712/74a59743-4730-4336-bdac-15f4031a73d5)
I only obtained the png data under "test-results", but did not obtain the ". tiff" data corresponding to "test-registered".

**Comment by xb-li** [comment]
Hi @cdgatenbee 
Later, I used two V100 files to execute this program, and although I obtained the ". tiff" data from the "test-registered" file, I output the following information:
![微信截图_20240113085240](https://github.com/MathOnco/valis/assets/92066712/30d2666f-1712-441c-af9d-b74520d04ce2)
I hope to receive your help again, thank you very much.
