### ISSUE TITLE
ValueError: array to be byte-swapped is read-only

### ISSUE THREAD

**Issue by smith6jt-cop** [MathOnco/valis#94]
Just reporting odd behavior and a workaround in case the information helps anyone.  After stitching 2D CODEX images with the MIST plugin in FIJI v1.54f with a macro, the output ome.tif files produce the following error in VALIS using Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64):

JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.

==== Converting images

Converting images:   0%|          | 0/4 [00:00<?, ?image/s]No series provided. Selecting series with largest image, which is series 0
Converting slide to pyvips image

Converting images:   0%|          | 0/4 [00:01<?, ?image/s]
/usr/local/src/valis/valtils.py:22: UserWarning: array to be byte-swapped is read-only
  warnings.warn(warning_msg, warning_type)
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/src/valis/slide_io.py", line 900, in tile2vips_threaded
    tile_array[idx] = slide_tools.numpy2vips(tile, self.metadata.pyvips_interpretation)
  File "/usr/local/src/valis/slide_tools.py", line 107, in numpy2vips
    linear.byteswap(inplace=True)
ValueError: array to be byte-swapped is read-only
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/src/valis/registration.py", line 4102, in register
    self.convert_imgs(series=self.series, reader_cls=reader_cls)
  File "/usr/local/src/valis/registration.py", line 2302, in convert_imgs
    vips_img = reader.slide2vips(level=level)
  File "/usr/local/src/valis/slide_io.py", line 966, in slide2vips
    self.get_tiles_parallel(level, tile_bbox, pixel_type, series, z=z, t=t),
  File "/usr/local/src/valis/slide_io.py", line 905, in get_tiles_parallel
    Parallel()(delayed(tile2vips_threaded)(i) for i in tqdm(range(n_tiles)))
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/usr/local/src/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
ValueError: array to be byte-swapped is read-only

JVM has been killed. If this was due to an error, then a new Python session will need to be started
Saving images: 0image [00:00, ?image/s]

The workaround is to simply resave the images as .tif files and then VALIS runs normally for registration.Valis and registrar.warp_and_save_slides.

Link to ome.tif file that raises error: https://drive.google.com/file/d/1jr7DX7BW0OR82mMzuyN_lGYV34uShw6_/view?usp=sharing
Link to resaved as .tif file that works: https://drive.google.com/file/d/1q461wAbrjtzRPRjlic13HrzzxNnJ8O8W/view?usp=sharing

**Comment by cdgatenbee** [comment]
Hi @smith6jt-cop, thanks for reporting this and for sharing the image. I've been working on improving valis' slide read/write functions, and this image seems to read OK with these changes. So, hopefully it will work without having to make this conversion in the next version (1.0.3), which I hope to push sometime this week.

Best,
-Chandler

**Comment by smith6jt-cop** [comment]
Sounds good and thanks again for your efforts.  If I can be of any assistance in helping with the changes, please let me know.

**Comment by cdgatenbee** [comment]
Hi @smith6jt-cop,
I just pushed the update (1.0.3) that has this fix. I tested reading the image you shared (thanks again!), and it reads without error, so hopefully it will resolve this issue for your other images too. 

Best,
-Chandler

**Comment by smith6jt-cop** [comment]
Awesome!  Thank again!  Is this version available as a Docker image?

Thanks,

Justin Smith, PhD
Dept of Pathology, Immunology, and Laboratory Medicine
UF Diabetes Institute
College of Medicine
1275 Center Drive, 5th Floor
Gainesville, FL 32610
